### ISSUE TITLE
Maya: add loaded containers to published instance GUI refresh issue

### ISSUE THREAD

**Issue by gabormarinov** [pypeclub/OpenPype#2900]
**Describe the bug**
Switching asset version in Maya in Manager GUI doesn't update the lines of the containers which loaded with the asset.

**To Reproduce**
1. Publish a layout which includes a model container. (layout v1 includes model v1)
2. Publish a new version of the model. (model v2)
3. Update the layout with the new model version and publish it. (layout v2 includes model v2)
4. layout v1 into an other workfile.
5. The manager GUI shows layout v1, model v1
6. Switch layout v1 to v2
7. The manager GUI shows layout v2, model v1 but in the maya scene model v1 swapped to v2 correctly.

**Expected behavior**
Manager GUI should correctly show the loaded model version.

**Comment by gabormarinov** [comment]
Maya 2020.4, OpenPype 3.9.1

**Comment by BigRoy** [comment]
I tested this in Maya 2020 on the latest `develop` branch and I cannot reproduce this issue. Upon updating the layout to a newer version which has a more recent model in it - I see the model update both visually in the scene and also in the Scene Inventory (the Manager from `OpenPype > Manage...`)

Can you confirm whether this issue is also present for you on the latest develop state?
Your particular issue might've been related to a bug in `3.9.1` releases. I think this might have been fixed by [this PR](https://github.com/pypeclub/OpenPype/pull/2944).

**Comment by gabormarinov** [comment]
I've checked it in 3.9.2-nightly.3 and the problem is still exist. The behaviour changed a bit, but I think it is still has flaws: 

1. publish "chair" (model) v1
2. load "chair" (model) v1 x2 into "twochairs" (layout) workfile and publish "twochairs" (layout) v1
3. load 'twochairs" (layout) v1 into "room" (layout) workfile and publish "room" (layout) v1
4. publish "chair" (model) v2
5. load "room" (layout) v1 workfile, it shows "chair"(model) v1 as outdated content as it should, update "chair" (model) to v2, and publish "room" (layout) v2
6. load "twochairs" (layout) v1 workfile, it shows "chair" (model) v1 as outdated content as it should, update "chair" (mode) to v2, and publish "twochairs" (layout) v2
7. load "room" (layout) v2 workfile. It shows in Manager, that "chair" (model) v2 is loaded, but in reality it is "chair" (model) v1. It also shows "twochairs" (layout) v1 as outdated as it should. After updating "twochairs" (layout) to v2, it re-references "chair" (model) v2, so now it is really loaded and in sync what Manager shows.

In step 7. after loading Maya scene should show "chair" (model) v2 and not v1. It shows v2 in manager but in reality it loads v1 which is visible in the scene.

**Comment by BigRoy** [comment]
@gabormarinov is this still relevant?

**Comment by gabormarinov** [comment]
@BigRoy I don't know, sorry. We skipped using the layout feature because it was buggy. I'm not sure I'll have time to check it in the year-end madness - but anyone could check it using the steps described.

**Comment by BigRoy** [comment]
No worries - just checking in whether this is a _current issue_ for you
